### ISSUE TITLE
High CPU usage after looking for Yubikey devices

### ISSUE THREAD

**Issue by obacker-snapcode** [Yubico/Yubico.NET.SDK#13] opened 2022-05-09 21:43 UTC
Hello!

Integrated the sdk in a desktop app and realized that it suddenly saw constantly high cpu usage. I moved this bit of code out to a console application:

```cs
var devices = YubiKeyDevice.FindAll();
await Task.Delay(-1);
```

Just this alone seems to be using alot of cpu, with or without inserted yubikey. After a quick inspection with dotTrace the api seems to be looking constantly for new inserted keys.

![image](https://user-images.githubusercontent.com/102969098/167503129-8ae546a8-65bd-459c-808c-4801aba917ff.png)

Whilst I imagine the high cpu usage is unintended, is there even a way to turn off this feature of background checking?

**Comment by GregDomzalski** [comment] 2022-05-12 18:27
What version of the SDK are you using?

Are you inserting more than one YubiKey in the system?

There was a bug in 1.2.0 that was addressed in 1.3.0 that cause high CPU usage on Windows in these cases. Based on the call tree you provided above (thanks for that!) it looks like it could be this same bug. Or, if you're on the latest 1.3.1... maybe there's yet another scenario that can trigger it.

Unfortunately, no, there's no way to shut off the background listener at this time.

**Comment by olabacker** [comment] 2022-05-13 05:43
I'm using version 1.3.1. 

I'm using either one or no yubikeys connected. After the `FindAll()` method has been executed the background listener seems to consume some cpu regardless. 

I've just glanced quickly in the source but it seems that there is no sleep duration in between the endless checking of devices but I might be wrong.

**Comment by GregDomzalski** [comment] 2022-05-13 15:59
Hmm. That's concerning if you're still encountering this in 1.3.1.

The call to SCardGetStatusChange is supposed to block until there is a difference in the system to report. Once we've processed all of the EventStates, we copy that over to the CurrentState, and the API will again block until there is something new in the EventState.

At least that's what's _supposed_ to happen. My guess is that this process is not quite happening properly.

Can you gather some logs for us? I'm using Serilog in the below example code because it supports adding thread IDs to the messages, which is helpful in this case. It logs to the console, but you may want to modify it to log to a file directly, instead.

```csharp
    class ThreadIdEnricher : ILogEventEnricher
    {
        public void Enrich(LogEvent logEvent, ILogEventPropertyFactory propertyFactory)
        {
            logEvent.AddPropertyIfAbsent(propertyFactory.CreateProperty(
                "ThreadId", Thread.CurrentThread.ManagedThreadId));
        }
    }
```

```csharp
// Put anywhere early on in your app, preferably before you first enumerate the
// SDK as that's when the listeners start.
            using var log = new LoggerConfiguration()
                .Enrich.With(new ThreadIdEnricher())
                .WriteTo.Console(
                    outputTemplate: "[{Level}] ({ThreadId})  {Message}{NewLine}{Exception}")
                .CreateLogger();

            Core.Logging.Log.LoggerFactory = LoggerFactory.Create(
                builder => builder
                    .AddSerilog(log)
                    .AddFilter(level => level >= LogLevel.Information));
```

**Comment by olabacker** [comment] 2022-05-14 12:22
Sure!

In the minimal example I provided before I simply added the logging capabilities you asked for. The logs start out like this and continue endless. This is the result on two different computers running win11. 

```
[Information] (1)  Creating WindowsHidDeviceListener.
[Information] (1)  Registered callback with ConfigMgr32.
[Information] (1)  Creating DesktopSmartCardDeviceListener.
[Error] (1)  "SCardEstablishContext" called and FAILED. Result = 8010001D
[Information] (1)  "SCardListReaders" called successfully.
[Information] (1)  Creating YubiKeyDeviceListener instance.
[Information] (11)  Smart card listener thread started. ThreadID is 11.
[Information] (1)  Performing initial cache population.
[Information] (1)  Entering write-lock.
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (1)  "SCardEstablishContext" called and FAILED. Result = 8010001D
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Warning] (1)  Exception caught: Yubico.PlatformInterop.SCardException: Unable to establish a connection to the platform's smartcard subsystem. Error code: 0x8010001d.
   at Yubico.Core.Devices.SmartCard.DesktopSmartCardDevice.GetList()
   at Yubico.Core.Devices.SmartCard.SmartCardDevice.GetSmartCardDevices()
   at Yubico.YubiKey.YubiKeyDeviceListener.GetFilteredSmartCardDevices(Transport transport)
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (1)  Found 0 HID devices and 0 Smart Card devices for processing.
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Information] (1)  Cache currently aware of 0 YubiKeys.
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (12)  YubiKey device listener thread started. ThreadID is 12.
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
[Information] (11)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [0 : UNAWARE]"]
[Error] (11)  "SCardGetStatusChange" called and FAILED. Result = 6
```

**Comment by GregDomzalski** [comment] 2022-05-15 22:43
Fascinating. So not only is the SDK chewing up 100% of one of your cores, it doesn't look like it's really working much at all. It looks like it was able to find the YubiKey over the keyboard interface, but that's it.

It looks like the SDK is unable to communicate with the smart card subsystem on Windows. And for some unknown reason, it is continuing along as if it can. I would have thought we'd have thrown an exception here... I'll have to do some digging into why it's not stopping when it clearly shouldn't continue.

Any idea why your application isn't able to talk to the smart card subsystem? I'll have to spin up a Windows 11 VM and try this out for myself. Any chance your app is running inside of a sandbox / UWP container?

**Comment by olabacker** [comment] 2022-05-15 23:11
Yes, the yubikey (neo) is found if inserted and I can do operations on it, which works fine. 

I'm not sure what exactly the smart card subsystem in windows is, but I'm not using any smart cards of any kind. 

I noticed the problem when I integrated the sdk into a WPF app (net6). Immediately afterwards I isolated the issue to a console application (net6) only containing the two lines in my original post (and then added your serilog code). Both of these apps (wpf and console) have the same problem on both win11 machines I tried it on. Both are running win11 natively so no vm.

If there is anything more I can help with logs or something else since it is easily reproducible here please let me know!

**Comment by olabacker** [comment] 2022-05-16 08:31
Another thing to add to the smart card discussion.. 

I realized the yubikey the has a CCID feature which was disabled when I checked the yubikey manager.

![image](https://user-images.githubusercontent.com/4084523/168550534-80c44695-4f6c-455e-bc06-fb15aaa9d0bf.png)

If I enable this interface the `FindAll()` method will  not complete successfully and instead throw the following exception

```
Yubico.PlatformInterop.SCardException
  HResult=0x80100069
  Message=Unable to establish a connection to the smart card in [Yubico Yubikey NEO OTP+U2F+CCID 0]. Error code: 0x80100069.
  Source=Yubico.Core
  StackTrace:
   at Yubico.Core.Devices.SmartCard.DesktopSmartCardDevice.Connect()
   at Yubico.YubiKey.CcidConnection..ctor(ISmartCardDevice smartCardDevice, YubiKeyApplication yubiKeyApplication)
   at Yubico.YubiKey.SmartCardDeviceInfoFactory.TryGetDeviceInfoFromManagement(ISmartCardDevice device, YubiKeyDeviceInfo& yubiKeyDeviceInfo)
   at Yubico.YubiKey.SmartCardDeviceInfoFactory.GetDeviceInfo(ISmartCardDevice device)
   at Yubico.YubiKey.YubiKeyDevice.YubicoDeviceWithInfo.GetDeviceInfo()
   at Yubico.YubiKey.YubiKeyDevice.YubicoDeviceWithInfo..ctor(IDevice device)
   at Yubico.YubiKey.YubiKeyDeviceListener.Update()
   at Yubico.YubiKey.YubiKeyDeviceListener..ctor()
   at Yubico.YubiKey.YubiKeyDeviceListener.<>c.<.cctor>b__34_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Yubico.YubiKey.YubiKeyDeviceListener.get_Instance()
   at Yubico.YubiKey.YubiKeyDevice.FindByTransport(Transport transport)
   at Yubico.YubiKey.YubiKeyDevice.FindAll()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\Ola\Github\YubikeyTest\Program.cs:line 20

  This exception was originally thrown at this call stack:
    [External Code]
    Program.<Main>$(string[]) in Program.cs
```

And here are the logs

```
[Information] (1)  Creating WindowsHidDeviceListener.
[Information] (1)  Registered callback with ConfigMgr32.
[Information] (1)  Creating DesktopSmartCardDeviceListener.
[Information] (1)  "SCardEstablishContext" called successfully.
[Information] (1)  "SCardListReaders" called successfully.
[Information] (1)  Creating YubiKeyDeviceListener instance.
[Information] (10)  Smart card listener thread started. ThreadID is 10.
[Information] (1)  Performing initial cache population.
[Information] (1)  Entering write-lock.
[Information] (10)  "SCardGetStatusChange" called successfully.
[Information] (10)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [1 : CHANGED]", "Yubico Yubikey NEO OTP+U2F+CCID 0: [0 : UNAWARE] => [3 : CHANGED, PRESENT]"]
[Information] (10)  "SCardListReaders" called successfully.
[Information] (10)  "SCardGetStatusChange" called successfully.
[Information] (10)  Reader states:
["\\\\?PnP?\\Notification: [0 : UNAWARE] => [1 : CHANGED]", "Yubico Yubikey NEO OTP+U2F+CCID 0: [0 : UNAWARE] => [3 : CHANGED, PRESENT]"]
[Information] (1)  "SCardEstablishContext" called successfully.
[Information] (1)  "SCardListReaders" called successfully.
[Information] (1)  Found 1 smart card devices.
[Information] (10)  SmartCardDevice instance created [path = "Yubico Yubikey NEO OTP+U2F+CCID 0", atr = "3B-FC-13-00-00-81-31-FE-15-59-75-62-69-6B-65-79-4E-45-4F-72-33-E1"]
[Information] (1)  "SCardGetStatusChange" called successfully.
[Information] (1)  Updated SCard reader states: ["Yubico Yubikey NEO OTP+U2F+CCID 0: [0 : UNAWARE] => [3 : CHANGED, PRESENT]"]
[Information] (10)  ISmartCardDevice "Smart Card: Yubico Yubikey NEO OTP+U2F+CCID 0" arrived.
[Information] (1)  SmartCardDevice instance created [path = "Yubico Yubikey NEO OTP+U2F+CCID 0", atr = "3B-FC-13-00-00-81-31-FE-15-59-75-62-69-6B-65-79-4E-45-4F-72-33-E1"]
[Information] (1)  Found 1 HID devices and 1 Smart Card devices for processing.
[Information] (1)  Cache currently aware of 0 YubiKeys.
[Information] (1)  Processing device "HID:1050:0116 Usage:Keyboard \\\\?\\HID#VID_1050&PID_0116&MI_00#8&3db766f&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\\KBD"
[Information] (1)  Handling an OTP slot request 19. Configuring = False
[Information] (1)  Wait for write pending...
[Information] (1)  Got write response ["TouchPending: False, ReadPending: False, WritePending: False, SequenceNumber: 0, Payload: 00-03-04-09-03-03-05"]
[Information] (1)  Wait for write pending...
[Information] (1)  Got write response ["TouchPending: False, ReadPending: False, WritePending: False, SequenceNumber: 0, Payload: 00-03-04-09-03-03-05"]
[Information] (1)  Wait for read pending...
[Information] (10)  "SCardGetStatusChange" called successfully.
[Information] (10)  Reader states:
["\\\\?PnP?\\Notification: [1 : UNAWARE] => [1 : UNAWARE]", "Yubico Yubikey NEO OTP+U2F+CCID 0: [3 : PRESENT] => [4 : CHANGED, EMPTY]"]
[Information] (10)  "SCardGetStatusChange" called successfully.
[Information] (10)  Reader states:
["\\\\?PnP?\\Notification: [1 : UNAWARE] => [1 : UNAWARE]", "Yubico Yubikey NEO OTP+U2F+CCID 0: [3 : PRESENT] => [4 : CHANGED, EMPTY]"]
[Information] (10)  SmartCardDevice instance created [path = "Yubico Yubikey NEO OTP+U2F+CCID 0", atr = "3B-FC-13-00-00-81-31-FE-15-59-75-62-69-6B-65-79-4E-45-4F-72-33-E1"]
[Information] (10)  ISmartCardDevice "Smart Card: Yubico Yubikey NEO OTP+U2F+CCID 0" removed.
[Information] (1)  Reset read mode ["TouchPending: False, ReadPending: False, WritePending: True, SequenceNumber: 15, Payload: 00-00-00-00-00-00-00"]
[Warning] (1)  Timed out after 1141ms.
[Warning] (1)  Exception encountered when trying to get device info from keyboard.
Yubico.YubiKey.KeyboardConnectionException: The YubiKey did not acknowledge a write to the keyboard interface within the alloted time.
   at Yubico.YubiKey.Pipelines.KeyboardTransform.WaitFor(Func`2 stopCondition, Boolean checkForTouch, Boolean shortTimeout, String timeoutMessage)
   at Yubico.YubiKey.Pipelines.KeyboardTransform.WaitForReadPending()
   at Yubico.YubiKey.Pipelines.KeyboardTransform.HandleSlotRequestInstruction(CommandApdu apdu, KeyboardFrameReader frameReader, Boolean configInstruction)
   at Yubico.YubiKey.Pipelines.KeyboardTransform.Invoke(CommandApdu commandApdu, Type commandType, Type responseType)
   at Yubico.YubiKey.Pipelines.OtpErrorTransform.Invoke(CommandApdu command, Type commandType, Type responseType)
   at Yubico.YubiKey.KeyboardConnection.SendCommand[TResponse](IYubiKeyCommand`1 yubiKeyCommand)
   at Yubico.YubiKey.KeyboardDeviceInfoFactory.TryGetDeviceInfoFromKeyboard(IHidDevice device, YubiKeyDeviceInfo& yubiKeyDeviceInfo)
[Information] (1)  Handling an OTP slot request 16. Configuring = False
[Information] (1)  Wait for write pending...
[Information] (1)  Got write response ["TouchPending: False, ReadPending: False, WritePending: False, SequenceNumber: 0, Payload: 00-03-04-09-03-03-05"]
[Information] (1)  Wait for write pending...
[Information] (1)  Got write response ["TouchPending: False, ReadPending: False, WritePending: False, SequenceNumber: 0, Payload: 00-03-04-09-03-03-05"]
[Information] (1)  Wait for read pending...
[Information] (1)  Reset read mode ["TouchPending: False, ReadPending: False, WritePending: True, SequenceNumber: 15, Payload: 00-00-00-00-00-00-00"]
[Information] (1)  Reading the OTP status.
[Information] (1)  Device appears to be a brand new YubiKey with serial 5249828
[Information] (1)  Processing device "Smart Card: Yubico Yubikey NEO OTP+U2F+CCID 0"
[Information] (1)  "SCardEstablishContext" called successfully.
[Error] (1)  "SCardConnect" called and FAILED. Result = 80100069
[Information] (1)  Context disposed.
[Information] (1)  CardHandle disposed.
```

Maybe this could be of some help.

**Comment by olabacker** [comment] 2022-07-20 13:40
Thanks, at first glance it seems like the problem is solved! I'll look further into it when I can

**Closed** 2022-08-04 22:23 UTC
